baseURL: "https://bazan.dev/"
relativeURLs: true
languageCode: en
timezone: "Asia/Singapore"
title: 'Ion Bazan'
disableKinds: [sitemap, RSS, taxonomy]
build:
  writeStats: true
outputFormats:
  html:
    mediaType: text/html
  txt:
    mediaType: text/plain
    isPlainText: true
    notAlternative: true
outputs:
  home: ["HTML", "TXT"]
  page: ["HTML"]
disableHugoGeneratorInject: true
params:
  isoDateFormat: "2006-01-02T15:04:05Z07:00"
  source: https://github.com/IonBazan/bazan.dev
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
services:
  googleAnalytics:
    ID: G-5ZGWNH0TXH
module:
  mounts:
    - source: "./node_modules/@fortawesome/fontawesome-free/webfonts"
      target: "static/webfonts"
