baseURL: "https://bazan.dev/"
relativeURLs: true
languageCode: en
title: 'Ion Bazan - Resume'
disableKinds: [sitemap, RSS]
outputFormats:
  HTML:
    baseName: myindex
build:
  writeStats: true
disableHugoGeneratorInject: true
