baseURL: "https://bazan.dev/"
relativeURLs: true
languageCode: en
timezone: "Asia/Singapore"
title: 'Ion Bazan - Resume'
disableKinds: [sitemap, RSS, taxonomy]
outputFormats:
  HTML:
    baseName: resume
build:
  writeStats: true
disableHugoGeneratorInject: true
params:
  isoDateFormat: "2006-01-02T15:04:05Z07:00"
  source: https://github.com/IonBazan/bazan.dev
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
