baseURL: "https://bazan.dev/"
languageCode: 'en-us'
title: 'Ion Bazan - Resume'
disableKinds: [sitemap, RSS]
outputFormats:
  HTML:
    baseName: myindex
build:
  writeStats: true
disableHugoGeneratorInject: true
