name: Trigger Vercel Build

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Vercel deployment
        run: |
          curl -X POST --fail-with-body ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
